In [1]:
import pandas

In [2]:
df=pandas.read_csv('MoviesOnStreamingPlatform.csv')
df

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Directors,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,87%,1,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,16740,The Ghosts of Buxley Hall,1980,NaN,6.2,NaN,0,0,0,1,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,120.0
16740,16741,The Poof Point,2001,7+,4.7,NaN,0,0,0,1,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90.0
16741,16742,Sharks of Lost Island,2013,NaN,5.7,NaN,0,0,0,1,Neil Gelinas,Documentary,United States,English,NaN
16742,16743,Man Among Cheetahs,2017,NaN,6.6,NaN,0,0,0,1,Richard Slater-Jones,Documentary,United States,English,NaN
16743,16744,In Beaver Valley,1950,NaN,NaN,NaN,0,0,0,1,James Algar,"Documentary,Short,Family",United States,English,32.0

In [3]:
df=df.drop(['Title','ID','Directors'],axis=1)

In [4]:
df

,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
0,2010,13+,8.8,87%,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1999,18+,8.7,87%,1,0,0,0,"Action,Sci-Fi",United States,English,136.0
2,2018,13+,8.5,84%,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0
3,1985,7+,8.5,96%,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,1966,18+,8.8,97%,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16739,1980,NaN,6.2,NaN,0,0,0,1,"Comedy,Family,Fantasy,Horror",United States,English,120.0
16740,2001,7+,4.7,NaN,0,0,0,1,"Comedy,Family,Sci-Fi",United States,English,90.0
16741,2013,NaN,5.7,NaN,0,0,0,1,Documentary,United States,English,NaN
16742,2017,NaN,6.6,NaN,0,0,0,1,Documentary,United States,English,NaN
16743,1950,NaN,NaN,NaN,0,0,0,1,"Documentary,Short,Family",United States,English,32.0

In [10]:
df.isnull().sum()

Year                      0
Age                    8844
IMDb                    333
Rotten Tomatoes       10954
Netflix                   0
Hulu                      0
Prime Video               0
Disney+                   0
Genres                    0
Country                   0
Language                  0
Runtime                 243
Rotten Tomatoes(%)    10954
dtype: int64

In [6]:
df=df.dropna(axis=0,subset=['Genres','Country','Language'])

In [7]:
def per(x):
    if not pandas.isna(x):
        x=x[:-1]
        return float(x)

In [8]:
df['Rotten Tomatoes(%)']=df['Rotten Tomatoes'].apply(per)

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\2801820217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rotten Tomatoes(%)']=df['Rotten Tomatoes'].apply(per)

In [9]:
df

,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Rotten Tomatoes(%)
0,2010,13+,8.8,87%,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,87.0
1,1999,18+,8.7,87%,1,0,0,0,"Action,Sci-Fi",United States,English,136.0,87.0
2,2018,13+,8.5,84%,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0,84.0
3,1985,7+,8.5,96%,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0,96.0
4,1966,18+,8.8,97%,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,1980,NaN,6.2,NaN,0,0,0,1,"Comedy,Family,Fantasy,Horror",United States,English,120.0,NaN
16740,2001,7+,4.7,NaN,0,0,0,1,"Comedy,Family,Sci-Fi",United States,English,90.0,NaN
16741,2013,NaN,5.7,NaN,0,0,0,1,Documentary,United States,English,NaN,NaN
16742,2017,NaN,6.6,NaN,0,0,0,1,Documentary,United States,English,NaN,NaN
16743,1950,NaN,NaN,NaN,0,0,0,1,"Documentary,Short,Family",United States,English,32.0,NaN

In [11]:
df['Genres']=df['Genres'].str.split(',')

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\2144546164.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Genres']=df['Genres'].str.split(',')

In [15]:
df['Country']=df['Country'].str.split(',')

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\3580391605.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country']=df['Country'].str.split(',')

In [17]:
df['Language']=df['Language'].str.split(',')

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\3691020346.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Language']=df['Language'].str.split(',')

In [23]:
df

,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Rotten Tomatoes(%)
0,2010,13+,8.8,87%,1,0,0,0,"[Action, Adventure, Sci-Fi, Thriller]","[United States, United Kingdom]","[English, Japanese, French]",148.0,87.0
1,1999,18+,8.7,87%,1,0,0,0,"[Action, Sci-Fi]",[United States],[English],136.0,87.0
2,2018,13+,8.5,84%,1,0,0,0,"[Action, Adventure, Sci-Fi]",[United States],[English],149.0,84.0
3,1985,7+,8.5,96%,1,0,0,0,"[Adventure, Comedy, Sci-Fi]",[United States],[English],116.0,96.0
4,1966,18+,8.8,97%,1,0,1,0,[Western],"[Italy, Spain, West Germany]",[Italian],161.0,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,1980,NaN,6.2,NaN,0,0,0,1,"[Comedy, Family, Fantasy, Horror]",[United States],[English],120.0,NaN
16740,2001,7+,4.7,NaN,0,0,0,1,"[Comedy, Family, Sci-Fi]",[United States],[English],90.0,NaN
16741,2013,NaN,5.7,NaN,0,0,0,1,[Documentary],[United States],[English],NaN,NaN
16742,2017,NaN,6.6,NaN,0,0,0,1,[Documentary],[United States],[English],NaN,NaN
16743,1950,NaN,NaN,NaN,0,0,0,1,"[Documentary, Short, Family]",[United States],[English],32.0,NaN

In [32]:
def cou(x):
    if 'United States' in x:
        return 1
    else:
        return 0

In [35]:
df['isInUS']=df['Country'].apply(cou)

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\1935929826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isInUS']=df['Country'].apply(cou)

In [36]:
def lan(x):
    if 'English' in x:
        return 1
    else:
        return 0

In [40]:
df['isInEng']=df['Language'].apply(lan)

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\1725432466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isInEng']=df['Language'].apply(lan)

In [47]:
def mul(x):
    if len(x)>=2:
        return 1
    else:
        return 0

In [48]:
df['isMultiCountry']=df['Country'].apply(mul)

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\3418403496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isMultiCountry']=df['Country'].apply(mul)

In [51]:
df['isMultiLanguage']=df['Language'].apply(mul)

C:\Users\chexi\AppData\Local\Temp\ipykernel_23988\3835732598.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['isMultiLanguage']=df['Language'].apply(mul)

In [58]:
df1=df.explode('Genres')

In [59]:
df2=df.explode('Country')

In [60]:
df3=df.explode('Language')

In [54]:
df.to_csv('movieData.csv',index=False)

In [64]:
df1.to_csv('movieDataGenres.csv',index=False)

In [65]:
df2.to_csv('movieDataCountry.csv',index=False)

In [66]:
df3.to_csv('movieDataLanguage.csv',index=False)

In [67]:
df

,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Rotten Tomatoes(%),isInUS,isInEng,isMultiCountry,isMultiLanguage
0,2010,13+,8.8,87%,1,0,0,0,"[Action, Adventure, Sci-Fi, Thriller]","[United States, United Kingdom]","[English, Japanese, French]",148.0,87.0,1,1,1,1
1,1999,18+,8.7,87%,1,0,0,0,"[Action, Sci-Fi]",[United States],[English],136.0,87.0,1,1,0,0
2,2018,13+,8.5,84%,1,0,0,0,"[Action, Adventure, Sci-Fi]",[United States],[English],149.0,84.0,1,1,0,0
3,1985,7+,8.5,96%,1,0,0,0,"[Adventure, Comedy, Sci-Fi]",[United States],[English],116.0,96.0,1,1,0,0
4,1966,18+,8.8,97%,1,0,1,0,[Western],"[Italy, Spain, West Germany]",[Italian],161.0,97.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,1980,NaN,6.2,NaN,0,0,0,1,"[Comedy, Family, Fantasy, Horror]",[United States],[English],120.0,NaN,1,1,0,0
16740,2001,7+,4.7,NaN,0,0,0,1,"[Comedy, Family, Sci-Fi]",[United States],[English],90.0,NaN,1,1,0,0
16741,2013,NaN,5.7,NaN,0,0,0,1,[Documentary],[United States],[English],NaN,NaN,1,1,0,0
16742,2017,NaN,6.6,NaN,0,0,0,1,[Documentary],[United States],[English],NaN,NaN,1,1,0,0
16743,1950,NaN,NaN,NaN,0,0,0,1,"[Documentary, Short, Family]",[United States],[English],32.0,NaN,1,1,0,0